# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltReviewer', '0003_auto_20180206_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
    ]
